FROM nginx:1.25.3-alpine

COPY default.conf /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/nginx.conf
COPY index.html /usr/share/nginx/html/index.html

RUN mkdir -p "/var/www/images" "/var/www/html/music"
COPY images/* /var/www/images
COPY music/song.mp3 /var/www/html/music
